Repository prgrms-aibe-devcourse/AIBE1_FinalProject_LastDance_BE, pull requests merged in 2025-08, with the labels that each got.

#179 fix: redis,jpa 명시 , thymeleaf 의존성 제거
  build.gradle
  src/main/java/store/lastdance/BeApplication.java
Labels: Fix

#182 fix: redis SSE 타임아웃 (TCP Keep-Alive 패킷)
  src/main/java/store/lastdance/config/RedisConfig.java
Labels: Fix

#184 fix: redis SSE 문제
  src/main/java/store/lastdance/config/RedisConfig.java
Labels: Fix

#197 fix: 헬스체크 실패 문제 해결
  build.gradle
  deploy.sh
  docker/docker-compose.yml
  monitoring/loki/config.yml
  monitoring/monitoring-compose.yml
  monitoring/prometheus/alert.rules
  monitoring/prometheus/prometheus.yml
  src/main/java/store/lastdance/repository/group/GroupRepository.java
  src/main/java/store/lastdance/service/image/ImageServiceImpl.java
  src/main/resources/application-prod.yml
Labels: Fix, Refactor

#198 fix: 메모리 추가
  .github/workflows/deploy.yml
  docker/docker-compose.yml
Labels: Refactor

#200 refactor: Loki 로깅 최적화 및 JVM 튜닝
  docker/docker-compose.yml
  monitoring/loki/config.yml
  monitoring/prometheus/alert.rules
  src/main/java/store/lastdance/scheduler/NotificationScheduler.java
  src/main/resources/application-prod.yml
Labels: Env, Refactor

#204 refector: 캘린더 예외처리, validate 정리, dto 정리
  src/main/java/store/lastdance/controller/calendar/CalendarController.java
  src/main/java/store/lastdance/domain/calendar/Calendar.java
  src/main/java/store/lastdance/dto/calender/request/CreateCalendarRequestDTO.java
  src/main/java/store/lastdance/dto/calender/request/UpdateCalendarRequestDTO.java
  src/main/java/store/lastdance/dto/calender/response/CalendarResponseDTO.java
  src/main/java/store/lastdance/dto/response/ApiResponse.java
  src/main/java/store/lastdance/exception/ErrorCode.java
  src/main/java/store/lastdance/repository/calendar/CalendarRepository.java
  src/main/java/store/lastdance/repository/group/GroupRepository.java
  src/main/java/store/lastdance/repository/user/UserRepository.java
  src/main/java/store/lastdance/scheduler/NotificationScheduler.java
  src/main/java/store/lastdance/service/calendar/CalendarService.java
  src/main/java/store/lastdance/service/calendar/CalendarServiceImpl.java
  src/main/java/store/lastdance/validation/calendar/CalendarValidator.java
Labels: Fix, Refactor, 코드 리뷰, Calendar

#217 refector: 캘린더 서비스/컨트롤러 V2 명명 규칙 적용
  src/main/java/store/lastdance/controller/calendar/CalendarV2Controller.java
  src/main/java/store/lastdance/converter/calendar/CalendarConverter.java
  src/main/java/store/lastdance/service/calendar/CalendarV2Service.java
  src/main/java/store/lastdance/service/calendar/CalendarV2ServiceImpl.java
Labels: Refactor, 코드 리뷰, Calendar
