Repository prgrms-aibe-devcourse/AIBE1_FinalProject_LastDance_BE, pull requests merged in 2025-07, with the labels that each got.

#152 refactor : Prompt DB에서 관리
  src/main/java/store/lastdance/domain/prompt/Prompt.java
  src/main/java/store/lastdance/exception/ErrorCode.java
  src/main/java/store/lastdance/repository/prompt/PromptRepository.java
  src/main/java/store/lastdance/service/admin/AdminServiceImpl.java
  src/main/java/store/lastdance/service/expense/ExpenseAnalyzerImpl.java
  src/main/java/store/lastdance/service/prompt/PromptService.java
Labels: Refactor, LLM, ADMIN

#153 refactor: LLM판결 오타 수정
  src/main/java/store/lastdance/repository/aijudgment/AiJudgmentRepository.java
  src/main/java/store/lastdance/service/admin/AdminServiceImpl.java
  src/main/java/store/lastdance/service/aijudgment/AiJudgmentServiceImpl.java
  src/test/java/store/lastdance/service/admin/AdminServiceTest.java
Labels: Refactor, LLM

#154 fix: 신규 가입자 추이 수정
  src/main/java/store/lastdance/service/admin/AdminServiceImpl.java
Labels: ADMIN

#156 feat: 트래픽 급증 알림 및 알림설정 변경
  monitoring/prometheus/alert.rules
  monitoring/prometheus/alertmanager.yml
Labels: Feat, Env, Fix

#157 fix : 트래픽 급증 문법수정
  monitoring/prometheus/alert.rules
Labels: Fix

#163 refactor: Gemini 503 에러 반환
  src/main/java/store/lastdance/exception/ErrorCode.java
  src/main/java/store/lastdance/service/expense/ExpenseAnalyzerImpl.java
Labels: Refactor

#165 refactor: SSE 끊김 문제 온라인 상태관리 로직 Redis로 변경 및 캘린더 무한루프방지
  src/main/java/store/lastdance/domain/notification/NotificationSetting.java
  src/main/java/store/lastdance/service/calendar/CalendarServiceImpl.java
  src/main/java/store/lastdance/service/notification/SSENotificationService.java
  src/main/java/store/lastdance/service/notification/SSENotificationServiceImpl.java
  src/main/java/store/lastdance/service/onlinestatus/OnlineStatusService.java
  src/main/java/store/lastdance/service/onlinestatus/OnlineStatusServiceImpl.java
Labels: Fix, Refactor, Notification

#166 fix: 무한 build-and-deploy 문제
  src/main/java/store/lastdance/service/notification/SSENotificationServiceImpl.java
Labels: Fix

#167 fix: Valkey ssl/tls 설정 문제
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: Fix

#171 env: logging 다시 원복
  src/main/resources/application-prod.yml
Labels: Env

#172 refactor: 로그인 시 403 OPTIONS CORS 허용
  src/main/java/store/lastdance/config/SecurityConfig.java
Labels: Refactor

#173 fix: 유령쿠키 제거로직
  src/main/java/store/lastdance/util/CookieUtils.java
Labels: Fix

#176 refactor: ECR -> GHCR로 변경
  .github/workflows/deploy.yml
  deploy.sh
Labels: Env, Refactor
